/*
 * CoordinateManager.h
 *
 *  Created on: Mar 16, 2010
 *      Author: juergens
 */

#ifndef COORDINATEMANAGER_H_
#define COORDINATEMANAGER_H_

/*
 $Id$

 Copyright (C) 2006 met.no

 Contact information:
 Norwegian Meteorological Institute
 Box 43 Blindern
 0313 OSLO
 NORWAY
 email: diana@met.no

 This file is part of generated by met.no

 This is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Tseries; if not, write to the Free Software
 Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 */
#include <QWidget>
#include <QString>
#include <QSlider>
#include <QLabel>
#include <QLineEdit>

class CoordinateManager : public QWidget {
Q_OBJECT
private:
  int value;
  int precision;
  int max;
  int min;

public:
  CoordinateManager(QWidget*, Qt::Orientation, QString);

  QSlider     * slider;
  QLineEdit   * edit;
  QLabel      * editLabel;
  QLabel      * sliderLabel;

  float getValue();
  void setValueToEdit();

public slots:
  void setValue(float v);
  void setValueBySlider(int v);
  void editValue(const QString& v);
  void setRange(int min, int max);
  void setPrecision(int p);

signals:
  void coordinatesChanged();


};

#endif /* COORDINATEMANAGER_H_ */
